<?php

/**
 * @file
 * Provides integration between the SMS Framework and Drupal users.
 */

define('SMS_USER_PENDING', 1);
define('SMS_USER_CONFIRMED', 2);
define('SMS_USER_ACTIVE', 3);

define('SMS_USER_MAX_CHARS', 140);

require_once 'sms_user.actions.inc';
require_once 'sms_user.rules.inc';

/**
 * Implementation of hook_perm()
 */
function sms_user_perm() {
  return array(
   'receive sms',
   'edit own sms number'
  );
}

/**
 * Implementation of hook_menu().
 */
function sms_user_menu() {
  $items = array();

  $items['admin/smsframework/sms_user'] = array(
    'title' => 'SMS User',
    'description' => 'Edit options for SMS and user integration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sms_user_admin_settings'),
    'access arguments' => array('administer sms'),
    'file' => 'sms_user.admin.inc',
  );

  $items['user/%user/edit/mobile'] = array(
    'title' => 'Mobile',
    'page callback' => 'sms_user_settings_page',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'sms_user_edit_access',
    'access arguments' => array(1),
    'tab_parent' => 'user/%/edit',
    'file' => 'sms_user.settings.inc',
  );

  $items['user/%user/edit/mobile/add'] = array(
    'title' => 'Add mobile number',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sms_user_settings_add_form', 1),
    'type' => MENU_CALLBACK,
    'access callback' => 'sms_user_edit_access', // @todo and not if set and no multiple
    'access arguments' => array(1),
    'file' => 'sms_user.settings.inc',
  );

  $items['user/%user/edit/mobile/%/delete'] = array(
    'title' => 'Delete mobile number',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sms_user_settings_delete_form', 1, 4),
    'type' => MENU_CALLBACK,
    'access callback' => 'sms_user_delete_access',
    'access arguments' => array(1, 4),
    'file' => 'sms_user.settings.inc',
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 */
function sms_user_theme() {
  return array(
    'sms_user_settings_page' => array(
      'arguments' => array('content' => NULL),
      'file' => 'sms_user.settings.inc',
    ),
    'sms_user_settings_active_form' => array(
      'arguments' => array('form' => NULL),
      'file' => 'sms_user.settings.inc',
    ),
    'sms_user_settings_confirm_form' => array(
      'arguments' => array('form' => NULL),
      'file' => 'sms_user.settings.inc',
    ),
  );
}

/**
 * Access control on edit users sms number.
 */
function sms_user_edit_access($account) {
  return (user_edit_access($account) && user_access('receive sms', $account));
}

/**
 * Access control on delete users sms number.
 */
function sms_user_delete_access($account, $number) {
  if (sms_user_edit_access($account)) {
    if ($account->uid == sms_user_get_uid($number)) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Send a message to a user.
 */
function sms_user_send($uid, $message) {
  $account = user_load($uid);

  if (user_access('receive sms', $account)) { //Check if the user is enabled to receive SMS
    if ($account->sms_user[0]['status'] == 2) {
      return sms_send($account->sms_user[0]['number'], $message, $account->sms_user[0]['gateway']);
    }
    else {
      return FALSE;
    }
  }
  else {
    drupal_set_message(t("User %user is not enabled to receive SMS, see 'receive sms' permission", array('%user' => $account->name)), 'status', TRUE);
  }
}

/**
 * Returns the uid of the owner of a number.
 */
function sms_user_get_uid($number, $status = NULL) {
  $sql = "SELECT uid FROM {sms_user} WHERE number = '%s'";
  $arguments = array($number);
  if (isset($status)) {
    $sql .= " AND status = %d";
    $arguments[] = $status;
  }
  $data = db_fetch_array(db_query($sql, $arguments));
  return $data['uid'];
}

/**
 * Implementation of hook_sms_send().
 */
function sms_user_sms_send(&$number, &$message, &$options, &$gateway) {
  if (variable_get('sms_user_sleep', 1) && $uid = sms_user_get_uid($number)) {
    $account = user_load(array('uid' => $uid, 'status' => 1));

    if (!empty($account->sms_user['sleep_enabled']) && _sms_user_sleep_active($account)) {
      unset($gateway['send']);
      watchdog('sms', 'Message was not sent to @user due to sleep settings.', array('@user' => $account->name));
    }
  }
}

/**
 * Is the user sleeping?
 *
 * @param $account
 *   User account object.
 *
 * @return
 *   TRUE if its currently in the user user sleep time.
 */
function _sms_user_sleep_active($account) {
  //if the user has a timezone set in his account get the time there
  if (!empty($account->timezone_name)) {
    $timezone = new DateTimeZone($account->timezone_name);
    $date = new DateTime();
    $date->setTimezone( $timezone );
    $current_hour = $date->format('G');
  }
  else {
    $current_hour = date('G');
  }

  if ($account->sms_user['sleep_start_time'] <= $current_hour && $account->sms_user['sleep_end_time'] > $current_hour) {
    return TRUE;
  }

  return FALSE;
}

function sms_user_send_confirmation($account, $number, $options) {
  $code = rand(1000, 9999);
  $number = sms_formatter($number);
  $data = array(
    'number'  => $number,
    'status'  => SMS_USER_PENDING,
    'code'    => $code,
    'gateway' => $options,
  );
  user_save($account, array('sms_user' => $data), 'mobile');
  sms_send($number, _sms_user_confirm_message($code), $options);
}

/**
 * Confirm a number with confirmation code.
 *
 * @param $account
 *   user object.
 * @param $number
 *   number to confirm.
 * @param $code
 *   confirmation code.
 * @param
 *   bool TRUE if only validating and not confirming.
 * @return
 *   bool TRUE if code correct for number.
 */
function sms_user_confirm($account, $number, $code, $validate = FALSE) {
  foreach ($account->sms_user as $acc_number) {
    if ($acc_number['number'] == $number) {
      if ($acc_number['code'] != $code) {
        // incorrect code.
        return FALSE;
      }
      if (! $validate) {
        $data = array(
          'number'  => $number,
          'status'  => isset($account->sms_user[1]) ? SMS_USER_CONFIRMED : SMS_USER_ACTIVE,
          'gateway' => $acc_number['gateway'],
        );

        user_save($account, array('sms_user' => $data), 'mobile');
        // If the rule module is installed, fire rules
        if (module_exists('rules')) {
          rules_invoke_event('sms_user_validated', $account);
        }
      }
      
      // correct code for number.
      return TRUE;
    }
  }

  // incorrect number.
  return FALSE;
}

function sms_user_validate_number(&$number) {
  if ($error = sms_validate_number($number)) {
    return $error;
  }
  elseif (sms_user_get_uid($number)) {
    return t('This phone number is already registered to another user.');
  }
}

/**
 * Implmentation of hook_user().
 */
function sms_user_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'load':
      return sms_user_load($account, $category);
    case 'update':
    case 'insert':
      return sms_user_save($edit, $account, $category);
    case 'view':
      if (user_access('receive sms', $account)) {
        if (isset($account->sms_user['status']) &&
	    $account->sms_user['status'] == SMS_USER_PENDING) {
          drupal_set_message(t('You need to confirm your mobile number, <a href="@mobile_url">enter the confirmation code sent to your mobile</a>.', array('@mobile_url' => url('user/'. $account->uid .'/edit/mobile'))));
        }
        $account->content['sms'] = array(
          '#type' => 'user_profile_category',
          '#title' => t('Mobile'),
        );
        $account->content['sms']['number'] = array(
          '#type' => 'user_profile_item',
          '#title' => t(''),
	  // @todo - theme function to format number.
          '#value' => isset($account->sms_user['number']) ? $account->sms_user['number'] : '',
        );
      }
      break;
    case 'register':
      return sms_user_register();
    case 'delete':
      return sms_user_delete($account->uid);
    case 'validate':
      if (!empty($edit['sms_user']) && (variable_get('sms_user_registration_form', 0) == 2 || strlen($edit['sms_user']['number']))) {
        if ($error = sms_user_validate_number($edit['sms_user']['number'])) {
          form_set_error('sms_user][number', $error);
        }
      }
      break;
    case 'login':
      // Check if first it's the user's first time logging in.
      if (!$account->access && !empty($account->sms_user['number']) && $account->sms_user['status'] < SMS_USER_CONFIRMED) {
        sms_user_send_confirmation($account, $account->sms_user['number'], $account->sms_user['gateway']);
        drupal_set_message(t('A confirmation message has been sent to your mobile phone. Please !link.', array('!link' => l(t('confirm your number'), 'user/'. $account->uid .'/edit/mobile'))), 'status');
      }
      break;
    case 'categories':
      $categories['mobile'] = array(
        'name' => 'mobile',
        'title' => t('Mobile'),
        'weight' => 10,
      );
      return $categories;
  }
}

/**
 * Load user mobile data into the user object.
 *
 * @todo this is called often, the $account->sms_user content could be 
 *   update and trusted?
 * @see sms_user_user()
 */
function sms_user_load(&$account, $category) {
  $account->sms_user = array();

  if (variable_get('sms_user_sleep', 1)) {
    // all the sms_user data is stored in {users}.data 
    // using this for sleep settings, 
    // but trusting the {sms_user} table for numbers
    $user_data = unserialize($account->data);
    $account->sms_user['sleep_enabled'] = $user_data['sms_user']['sleep_enabled'];
    $account->sms_user['sleep_start_time'] = $user_data['sms_user']['sleep_start_time'];
    $account->sms_user['sleep_end_time'] = $user_data['sms_user']['sleep_end_time'];
  }

  $result = db_query("SELECT number, status, code, gateway FROM {sms_user} WHERE uid = %d", $account->uid);

  while ($data = db_fetch_array($result)) {
    $data['gateway'] = unserialize($data['gateway']);

    /**
     * At present modules access $sms_user['field'] 
     * or $sms_user[0]['field'] to get the active number's 'field'.
     */
    if ($data['status'] == SMS_USER_ACTIVE) {
      array_unshift($account->sms_user, $data);
      array_merge($account->sms_user, $data);
    }
    else {
      $account->sms_user[] = $data;
    }
  }
}

/**
 * Save user module data.
 *
 * @see sms_user_user()
 */
function sms_user_save(&$edit, &$account, $category) {
  if (($category == 'mobile' || $category == 'account') && $edit['sms_user']) {
    $number = $edit['sms_user'];
    $number['gateway'] = serialize($number['gateway']);
    $number['uid'] = $account->uid;

    drupal_write_record('sms_user', $number, array('number', 'uid'));
    if (! db_affected_rows()) {
      $result = drupal_write_record('sms_user', $number);
    }

    $account->sms_user = $edit;
  }
}

/**
 * Deletes a user's mobile information from the database
 *
 * @param $uid
 *   The uid of the user who's data is to be removed.
 * @param $number
 *   The number to delete. Defaults to FALSE which will delete all numbers.
 *
 * Note: this doesn't delete from $account->sms_user that removed on re-load.
 *
 * @see sms_user_user()
 */
function sms_user_delete($uid, $number = FALSE) {
  $db_args = array($uid);

  if ($number == FALSE) {
    $number_where = '';
  }
  else {
    $number_where = "AND number = '%s'";
    $db_args[] = $number;
  }
  db_query("DELETE FROM {sms_user} WHERE uid = %d $number_where", $db_args);
}

/**
 * Set active number.
 *
 * For sms_user_multiple_numbers.
 *
 * @param $uid
 *   User id.
 * @param $number
 *   Mobile number to set as default.
 */
function sms_user_active_set($uid, $number) {
  db_query('UPDATE {sms_user} SET status = %d WHERE uid = %d AND status = %d', SMS_USER_CONFIRMED, $uid, SMS_USER_ACTIVE);
  db_query("UPDATE {sms_user} SET status = %d WHERE uid = %d AND number = '%s'", SMS_USER_ACTIVE, $uid, $number);
}

/**
 * Create a confirmation message sent to a user, this contains a code which is
 * used to confirm that the number is actually correct.
 *
 * @param $code
 *   Random code to send to user.
 *
 * @return $text
 *   Created message, ready to send to user.
 */
function _sms_user_confirm_message($code) {
  $text_format = variable_get('sms_user_confirmation_message', '[site-name] confirmation code: [confirm-code]');
  $text = token_replace_multiple($text_format, array('sms_user' => array('confirm-code' => $code)));
  return $text;
}

/**
 * Form elements to show on user registration page.
 *
 * @see sms_user_user()
 */
function sms_user_register() {
  if (variable_get('sms_user_registration_form', 0)) {
    $form['sms_user'] = array(
      '#type' => 'fieldset',
      '#title' => t('Mobile settings'),
      '#description' => t('You will receive a message to confirm your mobile information upon login.'),
      '#collapsible' => TRUE,
      '#tree' => TRUE,
    );

    $required = FALSE;
    if (variable_get('sms_user_registration_form', 0) == 2) {
      $required = TRUE;
    }
    $form['sms_user'] += sms_send_form($required);
    return $form;
  }
}

/**
 * Implementation of hook_token_values()
 */
function sms_user_token_values($type, $object = NULL, $options = array()) {
  global $user;
  $values = array();

  switch ($type) {
    case 'sms_user':
      $values['confirm-code'] = $object['confirm-code'];
      $values['mobile-url']   = url("user/$user->uid/edit/mobile", array('absolute' => TRUE));
      break;
  }
  return $values;
}

/**
 * Implementation of hook_token_list()
 */
function sms_user_token_list($type = 'all') {
  $tokens = array();
  if ($type == 'sms_user') {
    $tokens['sms_user']['confirm-code']    = t('The mobile confirmation code for the user.');
    $tokens['sms_user']['mobile-url']      = t('The URL for the user\'s mobile settings page.');
  }

  return $tokens;
}

/**
 * Implementation of hook_sms_incoming().
 */
function sms_user_sms_incoming($op, $number, $message, $options) {
  global $user;

  switch ($op) {
    case 'pre process':
      if ($account = sms_user_authenticate($number)) {
        $metadata = array(
          'login' => TRUE,
          'number' => $number,
          'message' => $message,
          'options' => $options,
        );
        sms_user_login_metadata($account->uid, $metadata);
        $edit = array();
        user_module_invoke('login', $edit, $account);
      }
      elseif (variable_get('sms_user_registration_enabled', 0) && $number) {
        if ($account = sms_user_register_new_user($number, $message, $options)) {
          // Send the new user the registration message if one exists.
          if ($message = variable_get('sms_user_new_account_message', '')) {
            sms_user_send($account->uid, $message);
          }
        }
      }
      break;
    case 'post process':
      sms_user_logout();
      break;
  }
}

/**
 * Store metadata related to SMS users registering/logging in.
 *
 * Drupal core doesn't really provide a way to pass user metadata around that's
 * related to a user registering (meaning during the registration cycle), so we
 * provide a storage mechanism here.
 *
 * Since it seems sloppy to handle registration cycles with one method and
 * logins with another, this function handles all SMS-related metadata related
 * to logging in and registering.
 *
 * The data is placed in this storage mechansim for the duration of the page
 * load, and is placed here before the user hooks are invoked by sms_user,
 * therefore it should be available to all modules that need it.
 *
 * @param $uid
 *   The uid of the user to store/fetch.  If NULL, return all cached accounts.
 * @param $metadata
 *   The metadata to store, or the metadata to fetch if NULL.
 *   The metadata is stored/retrieved as an associative array with the following
 *   key/value pairs:
 *
 *     'register' => A boolean indicating if the user is just registering.
 *     'login'    => A boolean indicating if the user is logging in.
 *     'number'   => The SMS number the message was sent from.
 *     'message'  => The SMS message sent with the registration/login.
 *     'options'  => The SMS message metadata passed from the gateway.
 *
 * @param $reset
 *   If TRUE, reset the accounts cache.
 *
 * @return
 *   No uid set: An array, key = uid, value = An associative array of account
 *               metadata.
 *   uid set, no metadata set: An associative array of account metadata.
 *   uid set, metadata set: Cache the metadata for the user, return TRUE.
 */
function sms_user_login_metadata($uid = NULL, $metadata = NULL, $reset = FALSE) {
  static $accounts = array();

  if ($reset) {
    $accounts = array();
  }

  if (!isset($uid)) {
    return $accounts;
  }

  if (isset($metadata)) {
    $accounts[$uid] = $metadata;
    return TRUE;
  }
  elseif (isset($accounts[$uid])) {
    return $accounts[$uid];
  }
  else {
    return FALSE;
  }
}

/**
 * Registers a new user via SMS
 *
 * @param $number
 *   The user's mobile number.
 * @param $message
 *   Body of the SMS message.
 * @param $options
 *   An associative array of metadata passed from the incoming gateway.
 * @return
 *   The user object of the created user.
 */
function sms_user_register_new_user($number, $message, $options) {
  global $user;

  $edit = array();

  // If we have a from address from the e-mail gateway, use it, otherwise
  // leave the e-mail fields blank.
  $mail = isset($options['sms_email_gateway_from']) ? $options['sms_email_gateway_from'] : '';

  // Pass in sms_user specific data for saving.
  $edit['sms_user'] = array(
    'number' => $number,
    'status' => 0,
    'code' => '',
    'gateway' => '',
  );

  // If by chance there's already a user with the same email address, then use
  // it instead of creating a new user.
  if ($mail && ($account = user_load(array('mail' => $mail)))) {
    $account = user_save($account, $edit);
  }
  else {
    $edit['mail'] = $edit['init'] = $mail;

    // Add password if enabled.
    if (variable_get('sms_user_allow_password', 0)) {
      $lines = explode("\n", $message);
      $words = explode(" ", $lines[0]);
      foreach ($words as $word) {
        if (trim($word)) {
          $edit['pass'] = preg_replace('/\s+/', '-', $word);
          break;
        }
      }
    }
    // Auto-generated password.
    if (!$edit['pass']) {
      $edit['pass'] = user_password();
    }

    // Pick a pseudo-random name for the user -- using the email
    // address would be a privacy violation.
    $edit['name'] = substr(md5($number . strval(time())), 0, 10);

    // Save the user.
    $edit['status'] = variable_get('user_register', 1) == 1;
    $account = user_save('', $edit);
  }


  // Verify that the account was created.
  if (is_object($account)) {
    $user = $account;

    $metadata = array(
      'register' => TRUE,
      'number' => $number,
      'message' => $message,
      'options' => $options,
    );
    sms_user_login_metadata($account->uid, $metadata);

    $edit = array();
    user_module_invoke('login', $edit, $account);

    return $account;
  }

  return FALSE;

}

/**
 * Authenticate a user based on mobile number.
 *
 * @param $number
 *   The number to authenticate against. For security, this should only be
 *   provided by incoming messages, not through user input.
 */
function sms_user_authenticate($number) {
  global $user;

  $uid = sms_user_get_uid($number);
  if ($account = user_load(array('uid' => $uid, 'status' => 1))) {
    $user = $account;
    watchdog('sms', '%name was authenticated using SMS.', array('%name' => $user->name));
    return $user;
  }
}

/**
 *
 */
function sms_user_logout() {
  global $user;

  // Destroy the current session:
  session_destroy();
  $user = drupal_anonymous_user();
}

/**
 * Helper function returns numbers array indexed by status, or number.
 *
 * @param $account
 *   User object.
 * @param $index
 *   string key to use to index.
 * @param $nocache
 *   bool set to true when user account could have just been updated.
 * @return 
 *   array numbers indexed by key value.
 */
function sms_user_numbers($account, $index, $nocache = FALSE) {
  static $numbers = array();

  if ($nocache) {
    $numbers[$account->uid] = array();
  }

  if (! isset($numbers[$account->uid][$index])) {
    foreach ($account->sms_user as $key => $number) {
      // skip the active number elements that are included as $sms_user['key'];
      if (! is_numeric($key) || ! is_array($number)) {
        continue;
      }
      if ($index == 'number') {
        $numbers[$account->uid][$index][$number[$index]] = $number;
      }
      else {
        $numbers[$account->uid][$index][$number[$index]][] = $number;
      }
    }
  }

  return $numbers[$account->uid][$index];
}

/**
 * Implementation of hook_views_api().
 */
function sms_user_views_api() {
  return array('api' => 2);
}

/**
 * Implements hook_usermerge_merge_users().
 *
 * Takes numbers from user to delete and adds them to user to keep.
 * @todo sleep settings.
 */
function sms_user_usermerge_merge_users($user_to_delete, $user_to_keep) {
  $numbers = db_query('SELECT * FROM {sms_user} WHERE uid = %d', $user_to_delete->uid);
  while ($number = db_fetch_object($numbers)) {
    $number->uid = $user_to_keep->uid;
    if (! drupal_write_record('sms_user', $number, 'number')) {
      // bail out - @todo error
      return;
    }
  }
}
